server:
  port: 8099

spring:
#  datasource:
#    dynamic:
#      enabled: true #启用动态数据源，默认true
#      primary: nana_shop #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
#      datasource:
#        nana:
#          url: jdbc:mysql:///goods
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        nana_shop:
#          url: jdbc:mysql:///cykjshop_good
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        #......省略
#        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
  redis:
    #redis服务器连接地址
    host: 42.193.140.71
    #端口号
    port: 6379
    #连接超时时间（毫秒）
    timeout: 10000
    #使用的redis库
    database: 1
    jedis:
      pool:
        #连接池最大连接数
        max-active: 10
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 2
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    password: 123456





